target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
"D",
"D203",  # incomaptible to D211
"D213",  # incompatible to D212
"PLW",
"TRY",
]

[lint.per-file-ignores]
"tests/*" = [
"S101",  # pytest provides assert introspection
]
